import turtle
turtle.shape("turtle")
turtle.color('violet', 'beige')
turtle.begin_fill()
size = 100
turtle.circle(35)
turtle.right(180)
turtle.circle(50)
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.right(90)
turtle.circle(70)
turtle.end_fill()
turtle.exitonclick()
